import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { AppShell } from "@/components/layout/app-shell";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.BETTER_AUTH_URL ?? "http://localhost:3000"),
  title: "Wangchao Intelligence",
  description: "Theme-first AI intelligence workspace for topic monitoring.",
};

// Nonce-based CSP requires request-time rendering so every framework and
// React Flight script can receive the nonce generated by proxy.ts.
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={GeistSans.className}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
