import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import { AppShell } from "@/components/layout/app-shell";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wangchao Intelligence",
  description: "Theme-first AI intelligence workspace for topic monitoring.",
};

// Nonce-based CSP requires request-time rendering so every framework and
// React Flight script can receive the nonce generated by proxy.ts.
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className={`${roboto.variable} ${GeistMono.variable}`}>
      <body className={roboto.className}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
