export interface DatabaseRuntimeBoundary {
  lazyInitializationRequired: true;
  target: "postgres-prisma";
}

export const databaseRuntimeBoundary: DatabaseRuntimeBoundary = {
  lazyInitializationRequired: true,
  target: "postgres-prisma",
};

export { disconnectPrismaClient, getPrismaClient } from "./client.js";
export { decryptCredential, encryptCredential, maskKeyHint } from "./crypto.js";
export {
  createCcpaymentInvoice,
  getCcpaymentOrderInfo,
  testCcpaymentCredential,
  verifyCcpaymentWebhookSignature,
  type CcpaymentConfig,
  type CreateInvoiceInput,
  type CreateInvoiceResult,
  type CcpaymentOrderInfo,
} from "./ccpayment.js";
export {
  createDeliveryLog,
  createPaymentInvoice,
  createReport,
  deleteByokCredential,
  deleteCcpaymentCredential,
  deletePreferenceMemory,
  deleteTelegramCredential,
  completeReport,
  failReport,
  findBriefingsForTelegramDelivery,
  findPaymentInvoiceByOrderId,
  findPendingDeliveryForBriefing,
  getActiveSourceCount,
  getByokCredentialView,
  getCcpaymentCredentialView,
  getDecryptedByokCredential,
  getDecryptedCcpaymentCredential,
  getDecryptedTelegramCredential,
  getInstantPushSettings,
  getMonthAiCallCount,
  getMonthExportCount,
  getReport,
  getSubscriptionPlanView,
  getTelegramCredentialView,
  getTodayAiCallCount,
  claimInstantPush,
  listInstantPushCandidates,
  listInstantPushOrganizations,
  markInstantPushFailed,
  markInstantPushSent,
  getTopicCount,
  listReports,
  listPendingReports,
  recordEnhancedFeedback,
  searchReportEvidenceEvents,
  setSelfHostedMode,
  setTelegramEnabled,
  setInstantPushEnabled,
  testTelegramCredential,
  updateDeliveryLog,
  updatePaymentInvoiceStatus,
  updatePreferenceMemoryWeight,
  updateReportStatus,
  updateSubscriptionPlan,
  upsertByokCredential,
  upsertCcpaymentCredential,
  upsertTelegramCredential,
  type ByokCredentialView,
  type CcpaymentCredentialView,
  type DeliveryLogRecord,
  type DecryptedByokCredential,
  type DecryptedTelegramCredential,
  type PaymentInvoiceRecord,
  type ReportEvidenceEvent,
  type ReportRecord,
  type SubscriptionPlanView,
  type TelegramCredentialView,
  type InstantPushCandidateRecord,
  type InstantPushLogRecord,
  type InstantPushOrganizationRecord,
  type InstantPushSettingsView,
} from "./extended-repositories.js";
export {
  attachActiveRssSource,
  assertMembershipRole,
  autoMuteFailingSources,
  batchUpdateSourceGovernanceStatus,
  canonicalizeUrl,
  completeTaskRun,
  createCandidateRssSource,
  createDailyBriefing,
  createPeriodBriefing,
  createSourceDiscoveryTaskRun,
  createSourceFetchTaskRun,
  createTaskRun,
  createTopic,
  createTopicWithActiveRssSource,
  deleteAiCredential,
  deleteSearchCredential,
  deleteTopic,
  ensureDefaultWorkspace,
  failTaskRun,
  getBriefingMarkdownForDownload,
  getDashboardEventById,
  getDecryptedCredentials,
  getEventMarkdownExportRecord,
  getSubscriptionCredentialView,
  getTopicById,
  listActiveSources,
  listActiveRssSourcesForFetch,
  listActiveTopics,
  listAllTopics,
  listAiModels,
  listCandidateRssSourcesForObservation,
  listDashboardEvents,
  listExpiredCandidateSources,
  listSavedDashboardEvents,
  listEventsForDailyBriefing,
  listFetchedItemsForAnalysis,
  listHighScoreEventPagesForDiscovery,
  listBriefingsPage,
  listItemsWithoutRawContent,
  listOrganizationMemberships,
  listPreferenceMemoryForDashboard,
  listRecentActiveSourcePagesForDiscovery,
  listRecentFeedbackSignals,
  listSourceGovernanceReport,
  listTimelineEvents,
  listTopicsForSourceDiscovery,
  listTopicSourceOverview,
  listUsageSummary,
  listUnreadEvents,
  mergeSemanticEvents,
  recordUsageEvent,
  recordCategoryPreferenceFeedback,
  recordSourceQualityObservation,
  recordSourceFetchSuccess,
  recordSourceFetchFailure,
  recordMarkdownExport,
  markItemFiltered,
  setSourceObserveExpiry,
  testAiCredential,
  testSearchCredential,
  updateDashboardEventState,
  updateItemRawContent,
  updateSourceGovernanceStatus,
  updateTopic,
  updateTopicStatus,
  upsertAiCredential,
  upsertPreferenceMemory,
  upsertIntelligenceEventFromItem,
  upsertFetchedItems,
  upsertSearchCredential,
  type AttachRssSourceInput,
  type AiCredentialTestInput,
  type AiModelListInput,
  type AiModelListResult,
  type BatchSourceGovernanceInput,
  type BatchSourceGovernanceResult,
  type BriefingEventRecord,
  type TimelineEventRecord,
  type BriefingPeriod,
  type AuditedTaskRunType,
  type CreateCandidateRssSourceInput,
  type CreateDailyBriefingInput,
  type CreatePeriodBriefingInput,
  type CreateSourceFetchTaskRunOptions,
  type CreateTaskRunInput,
  type CreateTopicInput,
  type CreateTopicWithRssSourceInput,
  type ExpiredCandidateSourceRecord,
  type RecordCategoryPreferenceFeedbackInput,
  type CredentialTestResult,
  type DashboardEventAction,
  type DashboardEventPage,
  type DashboardEventRecord,
  type DashboardBriefingRecord,
  type DashboardBriefingPage,
  type DecryptedAiCredential,
  type DecryptedCredentials,
  type DecryptedSearchCredential,
  type FeedbackSignalRecord,
  type FetchedSourceRecord,
  type IntelligenceEventWriteInput,
  type NormalizedFetchedItemInput,
  type OrganizationMembershipRecord,
  type PendingAnalysisItem,
  type PreferenceMemoryRecord,
  type RecordMarkdownExportInput,
  type RecordSourceQualityObservationInput,
  type RecordUsageEventInput,
  type SearchCredentialTestInput,
  type SourceDiscoveryPageRecord,
  type SourceDiscoveryTopicRecord,
  type SourceGovernanceAction,
  type SourceGovernanceRecord,
  type SubscriptionCredentialView,
  type TenantScope,
  type TopicDetailRecord,
  type TopicListItem,
  type TopicScope,
  type UpdateTopicInput,
  type UsageSummaryRecord,
  type UpsertPreferenceMemoryInput,
  type UpdateSourceGovernanceStatusInput,
  type WorkspaceSeed,
} from "./repositories.js";
