export interface DatabaseRuntimeBoundary {
  lazyInitializationRequired: true;
  target: "postgres-prisma";
}

export const databaseRuntimeBoundary: DatabaseRuntimeBoundary = {
  lazyInitializationRequired: true,
  target: "postgres-prisma",
};

export { disconnectPrismaClient, getPrismaClient } from "./client.js";
export { decryptCredential, encryptCredential, maskKeyHint } from "./crypto.js";
export {
  createDeliveryLog,
  createReport,
  deletePreferenceMemory,
  deleteTelegramCredential,
  completeReport,
  failReport,
  findBriefingsForTelegramDelivery,
  findPendingDeliveryForBriefing,
  getDecryptedTelegramCredential,
  getReport,
  getTelegramCredentialView,
  listReports,
  recordEnhancedFeedback,
  searchReportEvidenceEvents,
  setTelegramEnabled,
  testTelegramCredential,
  updateDeliveryLog,
  updatePreferenceMemoryWeight,
  updateReportStatus,
  upsertTelegramCredential,
  type DeliveryLogRecord,
  type DecryptedTelegramCredential,
  type ReportEvidenceEvent,
  type ReportRecord,
  type TelegramCredentialView,
} from "./extended-repositories.js";
export {
  attachActiveRssSource,
  assertMembershipRole,
  canonicalizeUrl,
  completeTaskRun,
  createCandidateRssSource,
  createDailyBriefing,
  createPeriodBriefing,
  createSourceDiscoveryTaskRun,
  createSourceFetchTaskRun,
  createTaskRun,
  createTopic,
  createTopicWithActiveRssSource,
  deleteAiCredential,
  deleteSearchCredential,
  deleteTopic,
  ensureDefaultWorkspace,
  failTaskRun,
  getBriefingMarkdownForDownload,
  getDashboardEventById,
  getDecryptedCredentials,
  getEventMarkdownExportRecord,
  getSubscriptionCredentialView,
  getTopicById,
  listAllTopics,
  listAiModels,
  listDashboardEvents,
  listSavedDashboardEvents,
  listEventsForDailyBriefing,
  listFetchedItemsForAnalysis,
  listHighScoreEventPagesForDiscovery,
  listActiveSources,
  listActiveRssSourcesForFetch,
  listActiveTopics,
  listBriefingsPage,
  listItemsWithoutRawContent,
  listOrganizationMemberships,
  listPreferenceMemoryForDashboard,
  listRecentFeedbackSignals,
  listRecentActiveSourcePagesForDiscovery,
  listSourceGovernanceReport,
  listTimelineEvents,
  listTopicsForSourceDiscovery,
  listTopicSourceOverview,
  listUsageSummary,
  listUnreadEvents,
  mergeSemanticEvents,
  recordUsageEvent,
  recordCategoryPreferenceFeedback,
  recordSourceQualityObservation,
  recordSourceFetchSuccess,
  recordSourceFetchFailure,
  recordMarkdownExport,
  markItemFiltered,
  testAiCredential,
  testSearchCredential,
  updateDashboardEventState,
  updateItemRawContent,
  updateSourceGovernanceStatus,
  updateTopic,
  updateTopicStatus,
  upsertAiCredential,
  upsertPreferenceMemory,
  upsertIntelligenceEventFromItem,
  upsertFetchedItems,
  upsertSearchCredential,
  type AttachRssSourceInput,
  type AiCredentialTestInput,
  type AiModelListInput,
  type AiModelListResult,
  type BriefingEventRecord,
  type TimelineEventRecord,
  type BriefingPeriod,
  type AuditedTaskRunType,
  type CreateCandidateRssSourceInput,
  type CreateDailyBriefingInput,
  type CreatePeriodBriefingInput,
  type CreateSourceFetchTaskRunOptions,
  type CreateTaskRunInput,
  type CreateTopicInput,
  type CreateTopicWithRssSourceInput,
  type RecordCategoryPreferenceFeedbackInput,
  type CredentialTestResult,
  type DashboardEventAction,
  type DashboardEventPage,
  type DashboardEventRecord,
  type DashboardBriefingRecord,
  type DashboardBriefingPage,
  type DecryptedAiCredential,
  type DecryptedCredentials,
  type DecryptedSearchCredential,
  type FeedbackSignalRecord,
  type FetchedSourceRecord,
  type IntelligenceEventWriteInput,
  type NormalizedFetchedItemInput,
  type OrganizationMembershipRecord,
  type PendingAnalysisItem,
  type PreferenceMemoryRecord,
  type RecordMarkdownExportInput,
  type RecordSourceQualityObservationInput,
  type RecordUsageEventInput,
  type SearchCredentialTestInput,
  type SourceDiscoveryPageRecord,
  type SourceDiscoveryTopicRecord,
  type SourceGovernanceAction,
  type SourceGovernanceRecord,
  type SubscriptionCredentialView,
  type TenantScope,
  type TopicDetailRecord,
  type TopicListItem,
  type TopicScope,
  type UpdateTopicInput,
  type UsageSummaryRecord,
  type UpsertPreferenceMemoryInput,
  type UpdateSourceGovernanceStatusInput,
  type WorkspaceSeed,
} from "./repositories.js";
