export interface DatabaseRuntimeBoundary {
  lazyInitializationRequired: true;
  target: "postgres-prisma";
}

export const databaseRuntimeBoundary: DatabaseRuntimeBoundary = {
  lazyInitializationRequired: true,
  target: "postgres-prisma",
};

export { disconnectPrismaClient, getPrismaClient } from "./client.js";
export {
  attachActiveRssSource,
  assertMembershipRole,
  canonicalizeUrl,
  completeTaskRun,
  createCandidateRssSource,
  createDailyBriefing,
  createSourceDiscoveryTaskRun,
  createSourceFetchTaskRun,
  createTopic,
  createTopicWithActiveRssSource,
  ensureDefaultWorkspace,
  failTaskRun,
  getBriefingMarkdownForDownload,
  getDashboardEventById,
  getEventMarkdownExportRecord,
  listDashboardEvents,
  listEventsForDailyBriefing,
  listFetchedItemsForAnalysis,
  listHighScoreEventPagesForDiscovery,
  listActiveSources,
  listActiveRssSourcesForFetch,
  listActiveTopics,
  listLatestBriefingsForDashboard,
  listOrganizationMemberships,
  listPendingTaskRuns,
  listPreferenceMemoryForDashboard,
  listRecentFeedbackSignals,
  listRecentActiveSourcePagesForDiscovery,
  listSourceGovernanceReport,
  listTopicsForSourceDiscovery,
  listTopicSourceOverview,
  listUsageSummary,
  listUnreadEvents,
  recordUsageEvent,
  recordSourceQualityObservation,
  recordSourceFetchSuccess,
  recordMarkdownExport,
  markItemFiltered,
  updateDashboardEventState,
  updateSourceGovernanceStatus,
  upsertPreferenceMemory,
  upsertIntelligenceEventFromItem,
  upsertFetchedItems,
  type AttachRssSourceInput,
  type BriefingEventRecord,
  type CreateCandidateRssSourceInput,
  type CreateDailyBriefingInput,
  type CreateSourceFetchTaskRunOptions,
  type CreateTopicInput,
  type CreateTopicWithRssSourceInput,
  type DashboardEventAction,
  type DashboardEventRecord,
  type DashboardBriefingRecord,
  type FeedbackSignalRecord,
  type FetchedSourceRecord,
  type IntelligenceEventWriteInput,
  type NormalizedFetchedItemInput,
  type OrganizationMembershipRecord,
  type PendingAnalysisItem,
  type PreferenceMemoryRecord,
  type RecordMarkdownExportInput,
  type RecordSourceQualityObservationInput,
  type RecordUsageEventInput,
  type SourceDiscoveryPageRecord,
  type SourceDiscoveryTopicRecord,
  type SourceGovernanceAction,
  type SourceGovernanceRecord,
  type TenantScope,
  type TopicScope,
  type UsageSummaryRecord,
  type UpsertPreferenceMemoryInput,
  type UpdateSourceGovernanceStatusInput,
  type WorkspaceSeed,
} from "./repositories.js";
